version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:3.3.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Run tests
          command: bundle exec rspec spec --tag ~@with_chromedriver

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
